apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started
  labels:
    app: getting-started
spec:
  replicas: 2
  selector:
    matchLabels:
      app: getting-started
  template:
    metadata:
      labels:
        app: getting-started
    spec:
      containers:
        - name: getting-started
          image: diya26/getting-started:v1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: getting-started-service
spec:
  type: LoadBalancer
  selector:
    app: getting-started
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
